# @file up-build.yml
#
# A workflow that builds UefiPayloadPackage's UPL and upload it's artifacts.
#
##
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent
##
name: UPL Build

on:
  workflow_dispatch:
  push:
    branches: ['master']

jobs:
  build_vs2022:
    strategy:
      matrix:
        os: [windows-latest]
        python-version: ['3.12']
        tool-chain: ['VS2022']
    name: Build UPL VS2022
    uses: ./.github/workflows/BuildPlatform.yml
    with:
      runs-on: ${{ matrix.os }}
      build-file: 'UefiPayloadPkg/PlatformCI/PlatformBuild.py'
      python-version: ${{ matrix.python-version }}
      tool-chain: ${{ matrix.tool-chain }}
      extra-build-args: 'FIT_BUILD=TRUE'
    secrets: inherit

  build_clang:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.12']
        tool-chain: ['CLANGDWARF']
    name: Build UPL CLANGDWARF
    uses: ./.github/workflows/BuildPlatform.yml
    with:
      runs-on: ${{ matrix.os }}
      build-file: 'UefiPayloadPkg/PlatformCI/PlatformBuild.py'
      python-version: ${{ matrix.python-version }}
      tool-chain: ${{ matrix.tool-chain }}
      extra-build-args: ''

  build_gcc:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.12']
        tool-chain: ['GCC']
    name: Build UPL GCC
    uses: ./.github/workflows/BuildPlatform.yml
    with:
      runs-on: ${{ matrix.os }}
      build-file: 'UefiPayloadPkg/PlatformCI/PlatformBuild.py'
      python-version: ${{ matrix.python-version }}
      tool-chain: ${{ matrix.tool-chain }}
      extra-build-args: 'FIT_BUILD=TRUE'